feature: 提交commands头部翻译
youngjuning/vscode-api-cn pull request #11
Opened 2021-08-16 15:18 UTC by Imchenlong

试水，提交命令行头部翻译

2021-08-16 15:48 UTC, youngjuning commented
@all-contributors please add @Imchenlong  for maintenance, translation, code

2021-08-17 01:11 UTC, youngjuning requested changes

2021-08-17 01:11 UTC, youngjunning commented on vscode.d.ts
> + * 该命名空间用于处理commands（命令）。 简而言之，commands是具有唯一标识符的函数，有时也称为命令处理程序。
中英文空格，原文的格式建议斜体格式建议保留。

2021-08-17 05:58 UTC, youngjuning commented on vscode.d.ts
> + * 该命名空间用于处理commands（命令）。 简而言之，commands是具有唯一标识符的函数，有时也称为命令处理程序。
统一成用于什么什么的命名空间吧

2021-08-17 14:26 UTC, pan463859 commented on vscode.d.ts
> + * 该命名空间用于处理commands（命令）。 简而言之，commands是具有唯一标识符的函数，有时也称为命令处理程序。
a command is a function with a unique identifier.
 翻成
 commands是具有唯一标识符的函数
感觉还挺好

2021-08-18 02:38 UTC, youngjuning commented on vscode.d.ts
> + * 该命名空间用于处理commands（命令）。 简而言之，commands是具有唯一标识符的函数，有时也称为命令处理程序。
Namespace for dealing with xxx：统一成 用于处理 xxx 的命名空间怎么样？ @pan463859  @Imchenlong

2021-08-21 12:44 UTC, closed without merging