feature/tests：finish Tests translate
youngjuning/vscode-api-cn pull request #12
Opened 2021-08-16 15:36 UTC by pan463859

translate of Tests part

2021-08-16 15:47 UTC, youngjuning commented
@all-contributors please add @pan463859  for maintenance, translation, ideas, code

2021-08-17 01:10 UTC, youngjuning requested changes

2021-08-17 01:10 UTC, youngjuning commented on vscode.d.ts
> + * 用于测试功能的命名空间。 通过注册
Tests 被通过注册  实例并添加  发布

2021-08-17 01:10 UTC, youngjuning commented on vscode.d.ts
> +	 * 创建一个新的 controller.
创建一个新的 test controller

2021-08-17 01:10 UTC, youngjuning commented on vscode.d.ts
> +	 * @param id controller的标识符, 必须全局唯一。
中英文空格

2021-08-17 01:46 UTC, youngjuning requested changes

2021-08-17 01:46 UTC, youngjuning commented on vscode.d.ts
> + * 用于测试功能的命名空间。通过注册 {@link TestController} 实例, 然后添加 {@link TestItem TestItems} 来发布测试。
```suggestion
 * 用于测试功能的命名空间。Tests 是通过注册 {@link TestController} 实例, 然后添加 {@link TestItem TestItems} 被发布的。
```

2021-08-18 01:58 UTC, youngjuning requested changes

2021-08-18 01:58 UTC, youngjunning commented on vscode.d.ts
> +	 * @param label controller的易于理解的标签。
```suggestion
	 * @param label controller 的易于理解的标签。
```

2021-08-18 01:58 UTC, youngjunning commented on vscode.d.ts
> +	 * @returns {@link TestController}实例。
```suggestion
	 * @returns {@link TestController} 实例。
```

2021-08-23 07:27 UTC, youngjuning approved these changes
![image](https://user-images.githubusercontent.com/13204332/130407427-46516791-e051-492f-87b8-861e4b0f82ff.png)

2021-08-23 07:28 UTC, merged